title: "Autill Website"
description: "Dies ist die Website für Autill"
baseurl: "" # Leerlassen für root
url: "https://autill.github.io/website" # Ihre GitHub Pages URL
markdown: kramdown
plugins:
  - jekyll-feed
