title: "Autill"
description: "Beschreibung Ihrer Website"
baseurl: "autill" # Setzen Sie dies auf den Repository-Namen
url: "https://autill.github.io" # Setzen Sie dies auf Ihre GitHub Pages URL


# url: "http://127.0.0.1:4000"

# url: "http://localhost:4000" 

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Permalinks
permalink: /:categories/:year/:month/:day/:title/

# Jekyll Feed
feed:
  path: atom.xml

# SEO and Sitemap
seo:
  name: "Ihre Website"
  description: "Beschreibung Ihrer Website"
  url: "https://autill.github.io/website"

sitemap:
  changefreq: "weekly"
  priority: 0.7
  
